---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go version
      - go env
      - go test
    when:
      branch:
        - master
  - name: build
    image: golang
    volumes:
      - name: deps
        path: /go
    environment:
      USERNAME:
        from_secret: username
      PASSWORD:
        from_secret: password
      A_SECRET:
        from_secret: a_secret
    commands:
      - echo $$USERNAME
      - echo $$PASSWORD
      - echo $$A_SECRET
      - go run . > test_secret.txt
      - cat test_secret.txt
      - go build

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
    - tag

volumes:
  - name: deps
    temp: {}