---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go version
      - go env
      - go test
    when:
      branch:
        - master
  - name: build
    image: golang
    volumes:
      - name: deps
        path: /go
    environment:
      USERNAME:
        from_secret: username
      PASSWORD:
        from_secret: password
      A_SECRET:
        from_secret: a_secret
    commands:
      - echo $$USERNAME
      - echo $$PASSWORD
      - echo $$A_SECRET
      - go run . > test_secret.txt
      - echo *********************
      - cat test_secret.txt
      - echo *********************
      - go build -o dist/
      - ls dist
      - echo $PWD

  - name: publish
    image: plugins/github-release
    environment:
      API_KEY:
        from_secret: API_KEY
    settings:
      api_key:
        from_secret: API_KEY
      files:
        - dist/*
        - bin/*
    when:
      event: tag

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
    - tag


notify:
  image: drillster/drone-email
  host: smtp.126.com
  username:
    from_secret: SMTP_USERNAME
  password:
    from_secret: SMTP_PASSWD
  from: drone@alex.drone.com
  when:
    status: [ changed, failure ]

volumes:
  - name: deps
    temp: {}